### PR TITLE
Loosening the check for gamename in the manifest with KK/KKS

### PR DESCRIPTION
**Pull request by takahiro0327**
I wanted to save myself the work of rewriting the manifesto.
I don't think this is right. But I think it is better than users spending their time manually rewriting it or asking others about it.

### CODE REVIEW

**Review by ManlyMarco — CHANGES_REQUESTED** [review]
This defeats the whole purpose of separating the two. You are no longer able to stop a mod from working in one or the other, which is absolutely necessary for some zipmods.
A lot of zipmods might appear to work but will break in subtle ways, usually shader-related. It's better to report zipmods that do work correctly in both games to anyone maintaining the modpack or to the modding channel on discord.

**Comment by takahiro0327** [comment]
Wouldn't the user take the action of trying to rewrite the manifest, and if it doesn't work, delete it?
Is it wrong to consider this modification as an automated rewrite?

**Comment by ManlyMarco** [comment]
When the manifest is modified manually, it is usually only one specific mod that the user wants to use. They will test the mod right away and see if it works or not.
If all mods are enabled right away, it is not possible to tell what is causing issues or not working.

**Comment by takahiro0327** [comment]
- Manually rewrite manifest without allowing unsupported zipmods to be in the directory
- Automatically rewrite manifest without allowing unsupported zipmods to be in the directory

If I had to choose between the two, I personally liked the latter one.

**Pull request closed without merging**
