### PR TITLE
PR for Issue #125 - Extended Save Data randomly going MIA

### PR DESCRIPTION
**Pull request by OrangeSpork**
As discussed here: https://github.com/IllusionMods/BepisPlugins/issues/125

Went with the Coroutine solution for 4 reasons:

1) Single code path (always more maintainable).
2) Always possible this issue does exist but more rarely in the older games and no one has tracked it back here yet.
3) The ConditionalWeakTable is really primitive in this version of .NET, the support to actually properly implement the WeakDictionary contract is in .Net 5, for example there is no Count support in this version of the runtime, now nothing is using that atm, but that's always dangerous.
4) ConditionalWeakTable is...really underaggressive at clean up. With the previous code or the coroutine approach I could load 6 characters in succession and then 3 coordinates and have my memory end up at ~10GB usage of 45 GB allocated of 64GB system. With ConditionalWeakTable is was at ~21GB. Loading and saving a bunch more characters and it went all the way to 40GB before stuff finally started collecting. Looks like it adopts a VERY lazy approach to GC and the interplay between that and the Unity GC pauses caused some lag spikes. Forcing some GC activity occasionally did some good things, but I wasn't feeling comfy with the whole thing...

### CODE REVIEW

**Comment by ManlyMarco** [comment]
This approach relies on the dictionary only being accessed form the main unity thread, if it was used in a separate thread then you would get the coroutine and the thread modifying the colllection at the same time. No idea if it's worth locking for, but it would prevent very annoying random issues at some later point if someone tries to use this dictionary in a thread. 

If you went with locking then it would be a good idea to use a timer instead of a coroutine. It all depends on how you want to handle cleanup requests (if you want to refresh the timer or if you want to run multiple timers). You can replicate refreshing a timer with a coroutine I think by putting the `WaitForSeconds` into a field and then changing its time field to reset it to 5.

With the current implementation there's a possibility of the cleanup running just as `Set` is called, producing the same issue as before. It would be much less frequent now, but it would still happen.

**Comment by OrangeSpork** [comment]
Well, now that I that I've managed to blindly stumble across the actual issue...better solution.

Fundamentally a hash based approach here has problems because hash equality and reference equality don't line up. Without some of the deeper support MS put into ConditionalWeakTable this actually isn't even possible to do formally correctly...but we can get close enough for what we need here I think.

Trick is to store ALL the references that have hash equivalent keys and hang onto them in weakreferenced key/value pairs lists. That way when we have all the references so when some GC we still have the others instead of replacing them with the latest and then losing the older copy which is actually the live longer one.

This approach isn't 'formally' correct because it's possible for different objects to generate the same hash, but considering these dictionaries are all of the same object type, the chance of two materially different objects of the same type generating the same hash is powerball level, I'll take those odds.

**Comment by OrangeSpork** [comment]
Dear Lord...helps if I actually _click_ the Push button...

**Comment by ManlyMarco** [comment]
Looks good, thank you!

**Pull request merged**
